config: DS_COMPONENT_TS7100_UTILS
version: "1.0.4"
tasks:
- cmd: ../ts7100-utils/build.sh
  cmd_type: cross
  description: Building ts7100-utils
- cmd: ../ts7100-utils/fetch.sh
  cmd_type: host
  description: Downloading ts7100-utils
- cmd: ../ts7100-utils/cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts7100-utils cross dependencies
