# Keep in mind this task is never enabled in a kconfig, or a dependency
# of any other task. This is only called from clean-cache.py
config: DS_CORE_CLEAN_CACHE
tasks:
# Clean cache from docker since it has files owned by root
- cmd: clean.sh
  cmd_type: docker
  dependencies:
    - DS_CORE_BUILD_HOST_DOCKER
  auto_create_rdepends: true
  description: Cleaning Work directory
