# Keep in mind this task is never enabled in a kconfig, or a dependency
# of any other task. This is only called from clean-cache.py
config: DS_CORE_CLEAN_CACHE
tasks:
- cmd: clean.sh
  cmd_type: host
  auto_create_rdepends: true
  description: Cleaning Work directory
