config: DS_TARGET_CHROOT_LATE
tasks:
- cmd: apt_update.sh
  cmd_type: target
  dependencies:
    - DS_TARGET_CHROOT_READY
  auto_create_rdepends: true
  description: Running late target rootfs chroot tasks
