config: DS_COMPONENT_TS7680_UTILS
version: "3.0.0"
tasks:
- cmd: fetch.sh
  cmd_type: host
  description: Downloading ts7680-utils

- cmd: cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts7680-utils cross dependencies

- cmd: build.sh
  cmd_type: cross
  description: Building ts7680-utils
