config: DS_COMPONENT_IDLEINJECT
version: "1.1.0"
tasks:
- cmd: fetch.sh
  cmd_type: host
  description: Downloading idleinject
- cmd: build.sh
  cmd_type: cross
  description: Building idleinject
- cmd: install.sh
  cmd_type: target
  description: Installing and Enabling idleinject.service
