config: DS_DOWNGRADE_WPA_HOSTAPD
version: "2.9.0"
pkg_version: "2.9.0-21+deb11u2~distroseed1"
tasks:
  - cmd: fetch.sh
    cmd_type: host
    description: Fetching binary packages
  - cmd: install.sh
    cmd_type: target
    description: Downgrading binary WPA packages
