config: DS_COMPONENT_TSMICROCTL
version: "1.0.3"
tasks:
- cmd: ../tsmicroctl/build.sh
  cmd_type: cross
  description: Building tsmicroctl
- cmd: ../tsmicroctl/fetch.sh
  cmd_type: host
  description: Downloading tsmicroctl
- cmd: ../tsmicroctl/install.sh
  cmd_type: target
  description: Installing and Enabling tsmicroctl.service
