config: DS_DISTRO_DEBIAN_11
tasks:
- cmd: ../../build.sh
  cmd_type: docker
  dependencies:
    - DS_CORE_MULTISTRAP_CONF
  provides: DS_DISTRO
  description: Fetching Debian 11 distribution
- cmd: sourceslist.sh
  cmd_type: host
  description: Adding sources.list
