config: DS_TARGET_APT_CONFIGURED
tasks:
- cmd: apt_finish_install.sh
  cmd_type: target
  dependencies:
    - DS_TARGET_CHROOT_EARLY
  provides: DS_TARGET_CHROOT_APT
  auto_create_rdepends: true
  description: Finishing target rootfs apt install
