# Use case configuration for TI tac5111 codec

Syntax 4

BootSequence [
        # Playback
        cset "name='OUT1x Config' 'Mono Single-ended at OUTxM only'"
        cset "name='ASI_RX_CH1_EN Switch' on"
        # Record
        cset "name='ADC1 Config' 'Single-ended mux INxM'"
        cset "name='ASI_TX_CH1_EN Switch' on"
        cset "name='ADC1 Digital Capture Volume' 255"
]
