config: DS_OUTPUT_GENIMAGE
tasks:
  - cmd: fetch-host-genimage.sh
    cmd_type: host
    description: Fetching host genimage

  - cmd: build-host-genimage.sh
    cmd_type: vm
    description: Building host genimage

  - cmd: generate_image.sh
    cmd_type: vm
    description: Running genimage to generate a disk image
    dependencies:
      - DS_OUTPUT_ROOTFS_EXT_GENERATED
    provides: DS_OUTPUT_GENIMAGE_GENERATED
    auto_create_rdepends: true

  - cmd: link-rootfs-dd.sh
    cmd_type: host
    description: Link target disk image output names
    dependencies:
      - DS_OUTPUT_GENIMAGE_GENERATED
