config: DS_COMPONENT_TS4100_UTILS
version: "3.0.0"
tasks:
- cmd: fetch.sh
  cmd_type: host
  provides: DS_ZPU_SRC
  description: Downloading ts4100-utils

- cmd: cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts4100-utils cross dependencies

- cmd: build.sh
  cmd_type: cross
  dependencies:
    - DS_CROSS_READY
    - DS_ZPU_COMPILER
    - DS_ZPU_SRC
  description: Building ts4100-utils
