config: DS_DISTRO_UBUNTU_22_04
tasks:
- cmd: ../../build.sh
  cmd_type: vm
  dependencies:
    - DS_CORE_PACKAGELIST
  provides: DS_DISTRO_ROOTFS
  description: Creating Ubuntu 22.04 target rootfs
- cmd: sourceslist.sh
  cmd_type: host
  description: Adding target apt sources
