config: DS_COMPONENT_TS4900_UTILS
version: "3.0.0"
tasks:
- cmd: fetch.sh
  cmd_type: host
  description: Downloading ts4900-utils

- cmd: cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts4900-utils cross dependencies

- cmd: build.sh
  cmd_type: cross
  description: Building ts4900-utils
