config: DS_TARGET_CHROOT_CLEAN
tasks:
- cmd: chroot_clean.sh
  cmd_type: vm
  dependencies:
    - DS_TARGET_CHROOT_LATE
  provides: DS_TARGET_ROOTFS_CLEANED
  auto_create_rdepends: true
  description: Cleaning target rootfs chroot environment
