#!/bin/bash -e

cd "${DS_TASK_WORK}"

mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="${DS_OVERLAY}/usr" -DCMAKE_C_FLAGS="-L${DS_TASK_WORK_DS_COMPONENT_LIBLVGL}/build/lib -L${DS_TASK_WORK_DS_COMPONENT_LV_DRIVERS}/build/lib -I${DS_TASK_WORK_DS_COMPONENT_LIBLVGL} -I${DS_TASK_WORK_DS_COMPONENT_LV_DRIVERS}" -DCMAKE_CXX_FLAGS="-L${DS_TASK_WORK_DS_COMPONENT_LIBLVGL}/build/lib -L${DS_TASK_WORK_DS_COMPONENT_LV_DRIVERS}/build/lib -I${DS_TASK_WORK_DS_COMPONENT_LIBLVGL} -I${DS_TASK_WORK_DS_COMPONENT_LV_DRIVERS}" -DCMAKE_TOOLCHAIN_FILE="${CMAKE_CROSS}"
make install
