config: DS_DISTRO_DEBIAN_13
tasks:
- cmd: ../../build.sh
  cmd_type: vm
  dependencies:
    - DS_CORE_PACKAGELIST
  provides: DS_DISTRO_ROOTFS
  description: Creating Debian 13 target rootfs
- cmd: sourceslist.sh
  cmd_type: host
  description: Adding target apt sources
