config: DS_COMPONENT_TS7100_UTILS
version: "2.0.0"
tasks:
- cmd: build.sh
  cmd_type: cross
  description: Building ts7100-utils
- cmd: fetch.sh
  cmd_type: host
  description: Downloading ts7100-utils
- cmd: cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts7100-utils cross dependencies
