config: DS_COMPONENT_TS7670_UTILS
version: "2.0.0"
tasks:
- cmd: ../ts7670-utils/fetch.sh
  cmd_type: host
  description: Downloading ts7670-utils

- cmd: ../ts7670-utils/cross-packages.sh
  cmd_type: packagelist-cross
  description: Adding ts7670-utils cross dependencies

- cmd: ../ts7670-utils/build.sh
  cmd_type: cross
  description: Building ts7670-utils
