#!/bin/bash -e

SOURCE="$DS_STAGING"

cd "$SOURCE"

mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="${DS_OVERLAY}/usr" -DCMAKE_C_FLAGS="-L${DS_STAGING_DS_COMPONENT_LIBLVGL}/build/lib -I${DS_STAGING_DS_COMPONENT_LIBLVGL} -I${DS_STAGING}" -DCMAKE_CXX_FLAGS="-L${DS_STAGING_DS_COMPONENT_LIBLVGL}/build/lib -I${DS_STAGING_DS_COMPONENT_LIBLVGL} -I${DS_STAGING}" -DBUILD_SHARED_LIBS=TRUE -DCMAKE_TOOLCHAIN_FILE="${CMAKE_CROSS}"
make install
