config: DS_CORE_COMBINE_OVERLAYS
tasks:
- cmd: combine.sh
  cmd_type: docker
  dependencies:
    - DS_DOCKER_READY
    - DS_DISTRO
  provides: DS_ROOTFS_COMBINED
  auto_create_rdepends: true
  description: Combining overlays into rootfs
