config: DS_TARGET_CHROOT_PREP
tasks:
- cmd: chroot_prep.sh
  cmd_type: vm
  dependencies:
    - DS_TARGET_ROOTFS_COMBINED
  provides: DS_TARGET_CHROOT_EARLY
  auto_create_rdepends: true
  description: Preparing target rootfs chroot environment
